server:
  port: 10013
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  application:
    name: store-product-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka